// Generated by gencpp from file arm_gazebo/FKRequest.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_FKREQUEST_H
#define ARM_GAZEBO_MESSAGE_FKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct FKRequest_
{
  typedef FKRequest_<ContainerAllocator> Type;

  FKRequest_()
    : joint_angles()
    , link_lengths()  {
    }
  FKRequest_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)
    , link_lengths(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_angles_type;
  _joint_angles_type joint_angles;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _link_lengths_type;
  _link_lengths_type link_lengths;





  typedef boost::shared_ptr< ::arm_gazebo::FKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::FKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FKRequest_

typedef ::arm_gazebo::FKRequest_<std::allocator<void> > FKRequest;

typedef boost::shared_ptr< ::arm_gazebo::FKRequest > FKRequestPtr;
typedef boost::shared_ptr< ::arm_gazebo::FKRequest const> FKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::FKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::FKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::FKRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::FKRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_angles == rhs.joint_angles &&
    lhs.link_lengths == rhs.link_lengths;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::FKRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::FKRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::FKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::FKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::FKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::FKRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::FKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::FKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::FKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a042249472409763a14cb741bdf7d15";
  }

  static const char* value(const ::arm_gazebo::FKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a04224947240976ULL;
  static const uint64_t static_value2 = 0x3a14cb741bdf7d15ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::FKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/FKRequest";
  }

  static const char* value(const ::arm_gazebo::FKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::FKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_angles\n"
"float64[] link_lengths\n"
;
  }

  static const char* value(const ::arm_gazebo::FKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::FKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
      stream.next(m.link_lengths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::FKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::FKRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_angles[i]);
    }
    s << indent << "link_lengths[]" << std::endl;
    for (size_t i = 0; i < v.link_lengths.size(); ++i)
    {
      s << indent << "  link_lengths[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.link_lengths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_FKREQUEST_H
