# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from arm_lib/Angles.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Angles(genpy.Message):
  _md5sum = "efc6069eeaa1308aece036b76bdc2160"
  _type = "arm_lib/Angles"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 x
float32 y
float32 z
float32 yx
float32 yy
float32 yz
float32 zx
float32 zy
float32 zz
float32 alpha
float32 beta
float32 gamma
float32 translationDist"""
  __slots__ = ['x','y','z','yx','yy','yz','zx','zy','zz','alpha','beta','gamma','translationDist']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,yx,yy,yz,zx,zy,zz,alpha,beta,gamma,translationDist

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Angles, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.yx is None:
        self.yx = 0.
      if self.yy is None:
        self.yy = 0.
      if self.yz is None:
        self.yz = 0.
      if self.zx is None:
        self.zx = 0.
      if self.zy is None:
        self.zy = 0.
      if self.zz is None:
        self.zz = 0.
      if self.alpha is None:
        self.alpha = 0.
      if self.beta is None:
        self.beta = 0.
      if self.gamma is None:
        self.gamma = 0.
      if self.translationDist is None:
        self.translationDist = 0.
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.yx = 0.
      self.yy = 0.
      self.yz = 0.
      self.zx = 0.
      self.zy = 0.
      self.zz = 0.
      self.alpha = 0.
      self.beta = 0.
      self.gamma = 0.
      self.translationDist = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_13f().pack(_x.x, _x.y, _x.z, _x.yx, _x.yy, _x.yz, _x.zx, _x.zy, _x.zz, _x.alpha, _x.beta, _x.gamma, _x.translationDist))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.x, _x.y, _x.z, _x.yx, _x.yy, _x.yz, _x.zx, _x.zy, _x.zz, _x.alpha, _x.beta, _x.gamma, _x.translationDist,) = _get_struct_13f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_13f().pack(_x.x, _x.y, _x.z, _x.yx, _x.yy, _x.yz, _x.zx, _x.zy, _x.zz, _x.alpha, _x.beta, _x.gamma, _x.translationDist))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.x, _x.y, _x.z, _x.yx, _x.yy, _x.yz, _x.zx, _x.zy, _x.zz, _x.alpha, _x.beta, _x.gamma, _x.translationDist,) = _get_struct_13f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13f = None
def _get_struct_13f():
    global _struct_13f
    if _struct_13f is None:
        _struct_13f = struct.Struct("<13f")
    return _struct_13f
